"""Initial Migration

Revision ID: 3f5e64b2ce37
Create Date: 2022-12-08 11:44:17.953003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f5e64b2ce37'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user__login',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('email', sa.String(length=500), nullable=True),
                    sa.Column('password', sa.String(length=500), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    with op.batch_alter_table('user__login', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user__login_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user__login', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user__login_email'))

    op.drop_table('user__login')
    # ### end Alembic commands ###
