"""Initial migration.

Revision ID: 7f15a4f0c89d
Revises: 
Create Date: 2024-03-09 19:19:20.170517

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f15a4f0c89d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('word_detection', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.drop_column('word_detection')

    # ### end Alembic commands ###
