"""Description of changes

Revision ID: d28d19d9d1fd
Revises: 7e9bfb4cb741
Create Date: 2024-03-02 18:20:58.418393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd28d19d9d1fd'
down_revision = '7e9bfb4cb741'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'daily_question', ['question_id'], ['id'])
        batch_op.drop_column('question')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('question', sa.VARCHAR(length=255), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('question_id')

    # ### end Alembic commands ###
