"""Initial migration.

Revision ID: f5cd77949b4a
Revises: 7f15a4f0c89d
Create Date: 2024-03-10 16:59:38.981860

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5cd77949b4a'
down_revision = '7f15a4f0c89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('daily_q_answer', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
